"""Configuration shared by the gateway and the daemon.

Both services read one TOML file (default /etc/agentos/services.toml,
generated by the NixOS modules). Missing keys fall back to DEFAULTS.
"""

import copy
import os
import re
import tomllib

DEFAULT_PATH = "/etc/agentos/services.toml"

DEFAULTS = {
    "redis": {
        "url": "unix:///run/redis-agentos/redis.sock?db=2",
    },
    "gateway": {
        "listen": "127.0.0.1",
        "port": 8080,
        "admin_socket": "/run/agentos-gateway/admin.sock",
        "log_dir": "/var/lib/agentos/logs",
        "pricing_file": "/etc/agentos/pricing.json",
        "upstream_timeout_sec": 600,
        "max_request_bytes": 64 * 1024 * 1024,
    },
    "budget": {
        "default_daily_usd": 50.0,
        "global_daily_usd": 500.0,
        "alert_thresholds": [50, 80, 95, 100],
        "auto_shutdown": True,
    },
    "limits": {
        "max_requests_per_minute": 60,
        "max_consecutive_failures": 5,
        "cooldown_sec": 300,
    },
    "providers": {
        "anthropic": {"base_url": "https://api.anthropic.com", "api": "anthropic"},
        "openai": {"base_url": "https://api.openai.com", "api": "openai"},
    },
    "daemon": {
        "state_dir": "/var/lib/agentos/state",
        "metrics_listen": "127.0.0.1",
        "metrics_port": 9950,
        "reap_interval_sec": 5,
    },
    "gpu": {
        # One file per exclusively held GPU, containing the holder's agent id
        "lock_dir": "/run/agentos/gpu",
        # A lock younger than this is never treated as stale (spawn is starting)
        "stale_grace_sec": 30,
    },
    "notify": {
        # Internal event types to forward (see daemon.EVENT_TEXT)
        "events": [],
        "targets": [],
    },
}

# Placeholder credential that tells the gateway to inject its own key
MANAGED_KEY = "agentos-managed"

_AGENT_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")


def valid_agent_id(agent_id):
    return bool(_AGENT_ID.match(agent_id or ""))


def _merge(base, override):
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(base.get(key), dict):
            _merge(base[key], value)
        else:
            base[key] = value
    return base


def load(path=None):
    """Load the services config, merged over DEFAULTS."""
    path = path or os.environ.get("AGENTOS_SERVICES_CONFIG", DEFAULT_PATH)
    cfg = copy.deepcopy(DEFAULTS)
    if path and os.path.exists(path):
        with open(path, "rb") as f:
            _merge(cfg, tomllib.load(f))
    # Providers added in the file may omit the api kind
    for name, prov in cfg["providers"].items():
        prov.setdefault("api", "anthropic" if name == "anthropic" else "openai")
    return cfg
