"""Configuration shared by the gateway and the daemon.

Both services read one TOML file (default /etc/agentos/services.toml,
generated by the NixOS modules). Missing keys fall back to DEFAULTS.
"""

import copy
import os
import re
import tomllib

DEFAULT_PATH = "/etc/agentos/services.toml"

DEFAULTS = {
    "redis": {
        "url": "unix:///run/redis-agentos/redis.sock?db=2",
    },
    "gateway": {
        "listen": "127.0.0.1",
        "port": 8080,
        "admin_socket": "/run/agentos-gateway/admin.sock",
        "log_dir": "/var/lib/agentos/logs",
        "pricing_file": "/etc/agentos/pricing.json",
        "upstream_timeout_sec": 600,
        "max_request_bytes": 64 * 1024 * 1024,
        # Agents must present the token registered by `agentos spawn` in
        # their URL (/agent/<id>:<token>/...); the unmanaged /<provider>/
        # path is then only served on the admin socket.
        "require_agent_tokens": True,
    },
    "budget": {
        "default_daily_usd": 50.0,
        "global_daily_usd": 500.0,
        "alert_thresholds": [50, 80, 95, 100],
        "auto_shutdown": True,
        # Hold an estimated cost (max output tokens + input size) before
        # forwarding, so concurrent requests cannot overshoot a budget
        "reserve": True,
        # Output allowance assumed when a request sets no max_tokens
        "default_max_tokens": 4096,
    },
    "limits": {
        "max_requests_per_minute": 60,
        "max_consecutive_failures": 5,
        "cooldown_sec": 300,
        # Failed agent authentications per client address and minute before
        # further failures answer 429 instead of 401; 0 disables
        "max_auth_failures_per_minute": 20,
        # Loop detection: the same request fingerprint K times in a row
        "loop_detection": True,
        "loop_repeat_threshold": 5,
        "loop_window_sec": 600,
        "loop_fingerprint_messages": 4,
    },
    "routing": {
        # "static" applies rewrites only; "cheapest" also picks the cheapest
        # model of an equivalence group
        "strategy": "static",
        # Global rewrites {"requested-model": "routed-model"}
        "rewrites": {},
        # Per agent-id-prefix rewrites {"prefix": {"requested": "routed"}}
        "agents": {},
        # Equivalence groups for strategy = "cheapest": [["model-a", "model-b"]]
        "groups": [],
        # Model -> provider that serves it, e.g. {"llama3.1": "local"}
        "targets": {},
        # Budget-aware downgrade: at >= threshold_pct of the agent's daily
        # budget, rewrite to models[<provider>]. 0 disables.
        "downgrade": {"threshold_pct": 0, "models": {}},
    },
    "recording": {
        "enabled": False,
        "dir": "/var/lib/agentos/recordings",
        "max_body_bytes": 64 * 1024 * 1024,
    },
    "bus": {
        "max_len": 1000,
        "max_message_bytes": 64 * 1024,
        "max_wait_sec": 30,
    },
    "providers": {
        "anthropic": {"base_url": "https://api.anthropic.com", "api": "anthropic"},
        "openai": {"base_url": "https://api.openai.com", "api": "openai"},
        # Other providers are added in services.toml, e.g.
        #   [providers.gemini]  base_url = "https://generativelanguage.googleapis.com"  api = "gemini"
        # Optional per provider: key_file, zero_cost (every model costs $0;
        # the default for api = "openai-compatible"), api_version (Azure),
        # timeout_sec, fallbacks (see docs/gateway-features.md).
    },
    "daemon": {
        "state_dir": "/var/lib/agentos/state",
        "metrics_listen": "127.0.0.1",
        "metrics_port": 9950,
        "reap_interval_sec": 5,
    },
    "gpu": {
        # One file per exclusively held GPU, containing the holder's agent id
        "lock_dir": "/run/agentos/gpu",
        # A lock younger than this is never treated as stale (spawn is starting)
        "stale_grace_sec": 30,
    },
    "notify": {
        # Internal event types to forward (see daemon.EVENT_TEXT)
        "events": [],
        "targets": [],
    },
}

# Provider api kinds the gateway has an adapter for (providers.py)
API_KINDS = ("anthropic", "openai", "openai-compatible", "azure-openai", "gemini")

# Placeholder credential that tells the gateway to inject its own key
MANAGED_KEY = "agentos-managed"

_AGENT_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")


def valid_agent_id(agent_id):
    return bool(_AGENT_ID.match(agent_id or ""))


def valid_topic(topic):
    """Bus topics look like agent ids; "@<agent-id>" is an agent's inbox."""
    topic = topic or ""
    return valid_agent_id(topic[1:] if topic.startswith("@") else topic)


def _merge(base, override):
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(base.get(key), dict):
            _merge(base[key], value)
        else:
            base[key] = value
    return base


def load(path=None):
    """Load the services config, merged over DEFAULTS."""
    path = path or os.environ.get("AGENTOS_SERVICES_CONFIG", DEFAULT_PATH)
    cfg = copy.deepcopy(DEFAULTS)
    if path and os.path.exists(path):
        with open(path, "rb") as f:
            _merge(cfg, tomllib.load(f))
    # Providers added in the file may omit the api kind
    for name, prov in cfg["providers"].items():
        prov.setdefault("api", "anthropic" if name == "anthropic" else "openai")
        if prov["api"] not in API_KINDS:
            raise ValueError("provider %r: unknown api %r (known: %s)" % (name, prov["api"], ", ".join(API_KINDS)))
    return cfg
