# AgentOS CLI — user-facing command for managing agents
#
# Configuration comes from /etc/agentos/runtime.json (generated by the
# runtime module); AGENTOS_RUNTIME overrides the path.
{ lib
, writeShellApplication
, coreutils
, curl
, gawk
, git
, gnugrep
, jq
, procps
, rsync
, util-linux
}:

writeShellApplication {
  name = "agentos";
  runtimeInputs = [ coreutils curl gawk git gnugrep jq procps rsync util-linux ];

  text = ''
    RUNTIME="''${AGENTOS_RUNTIME:-/etc/agentos/runtime.json}"
    VERSION="0.3.0"

    if [ -t 2 ]; then
      RED='\033[0;31m' GREEN='\033[0;32m' YELLOW='\033[1;33m' BLUE='\033[0;34m' BOLD='\033[1m' NC='\033[0m'
    else
      RED="" GREEN="" YELLOW="" BLUE="" BOLD="" NC=""
    fi
    info() { echo -e "''${BLUE}[INFO]''${NC} $*" >&2; }
    ok()   { echo -e "''${GREEN}[OK]''${NC} $*" >&2; }
    warn() { echo -e "''${YELLOW}[WARN]''${NC} $*" >&2; }
    err()  { echo -e "''${RED}[ERR]''${NC} $*" >&2; }
    die()  { err "$*"; exit 1; }

    [ -r "$RUNTIME" ] || die "$RUNTIME not found; is agentos.runtime enabled?"
    conf() { jq -r "$1" "$RUNTIME"; }
    WORKSPACE_ROOT=$(conf .workspace_root)
    STATE_DIR=$(conf .state_dir)
    LOG_DIR=$(conf .log_dir)
    AGENT_USER=$(conf .agent_user)
    AGENT_HOME=$(conf .agent_home)
    GATEWAY=$(conf .gateway_url)
    ADMIN_SOCKET=$(conf .admin_socket)
    GATEWAY_ENABLED=$(conf .gateway_enabled)
    SNAPSHOT_DIR=/var/lib/agentos/snapshots
    DEFAULT_ISOLATION=$(conf '.default_isolation // "sandbox"')
    CONTAINER_ENABLED=$(conf '.container.enabled // false')
    NETNS_HELPER=$(conf '.container.netns_helper // empty')
    CONTAINER_GATEWAY=$(conf '.container.gateway_url // empty')
    GPU_ENABLED=$(conf '.gpu.enabled // false')
    GPU_HELPER=$(conf '.gpu.helper // empty')
    PULLRUN_ENABLED=$(conf '.pullrun.enabled // false')
    PULLRUN_BIN=$(conf '.pullrun.bin // empty')
    PULLRUN_SOCKET=$(conf '.pullrun.socket // empty')
    PULLRUN_IMAGE=$(conf '.pullrun.image // empty')
    PULLRUN_LOG_DIR=$(conf '.pullrun.log_dir // empty')
    PULLRUN_GATEWAY=$(conf '.pullrun.gateway_url // empty')

    valid_name() { [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$ ]]; }
    state_file() { echo "$STATE_DIR/$1.json"; }
    running_count() {
      local n=0 f
      for f in "$STATE_DIR"/*.json; do
        [ -e "$f" ] || continue
        if [ "$(jq -r .status "$f" 2>/dev/null)" = "running" ]; then
          n=$((n + 1))
        fi
      done
      echo "$n"
    }
    need_sudo() {
      sudo -n true 2>/dev/null || die "this needs passwordless sudo (agent units are started as root)"
    }
    admin_api() {
      local method="$1" path="$2"
      local args=(-fsS --unix-socket "$ADMIN_SOCKET" -X "$method" -H 'Content-Type: application/json')
      if [ $# -ge 3 ]; then
        args+=(--data "$3")
      fi
      curl "''${args[@]}" "http://localhost/_agentos/$path"
    }

    # ── help ──────────────────────────────────────────────────────────
    cmd_help() {
      cat <<'HELP'
    AgentOS — an OS for coding agents

    USAGE:
        agentos <COMMAND> [OPTIONS]

    AGENTS:
        agents                     List available agents
        spawn <agent> [options] [-- agent args]
            --workspace <name|path>  Workspace (default: current directory)
            --budget <usd>           Daily budget for this agent
            --model <name>           Exported as AGENTOS_MODEL
            --isolation <mode>       sandbox (default) or container: own root
                                     filesystem, PID/IPC/hostname and network
                                     namespaces (bridge agentos0)
                                     pullrun (experimental): headless agent in a
                                     Pullrun container, see docs/pullrun.md
            --gpu [N|any]            Reserve GPU N (or a comma list, or any
                                     free one) exclusively for this agent
            --unsandboxed            Run as yourself instead of agentos-agent
        list                       Running and recent agents with today's spend
        logs <id> [-f]             Model API calls made by an agent
        kill <id>                  Stop an agent
        shell <id>                 Shell inside a running agent's sandbox
        gpu                        GPUs and which agent holds each
        status                     Service health and totals

    WORKSPACES:
        workspace create <name> [--from <git-url|path>]
        workspace list
        workspace rm <name>
        snapshot [name]            Snapshot all workspaces (btrfs)
        snapshots                  List snapshots
        rollback <snapshot> <workspace>

    OTHER:
        budget ...                 Same as agentos-budget
        install <pkg>              nix profile install nixpkgs#<pkg>
        search <query>             nix search nixpkgs <query>
        version | help
    HELP
    }

    cmd_version() { echo "AgentOS $VERSION"; }

    # Agents installed from the marketplace (`agentos-market install`) are
    # listed in $AGENTS_D/*.json as {"agents": {"<name>": "<store path>"}}.
    # Only executables inside the Nix store or the system profile are used.
    AGENTS_D=/var/lib/agentos/agents.d
    extension_agent() {
      local f path
      for f in "$AGENTS_D"/*.json; do
        [ -e "$f" ] || continue
        path=$(jq -r --arg a "$1" '.agents[$a] // empty' "$f" 2>/dev/null) || continue
        if [[ "$path" =~ ^(/nix/store|/run/current-system)/[^[:space:]]+$ && "$path" != *..* && -x "$path" ]]; then
          echo "$path"
          return
        fi
      done
    }

    cmd_agents() {
      echo "Agents (agentos spawn <name>):"
      jq -r '.agents | to_entries | group_by(.value)[] | "  \(map(.key) | join(", "))\t-> \(.[0].value)"' "$RUNTIME" \
        | column -t -s $'\t'
      local f
      for f in "$AGENTS_D"/*.json; do
        [ -e "$f" ] || continue
        jq -r '.agents // {} | to_entries[] | "  \(.key)\t-> \(.value) (marketplace)"' "$f" 2>/dev/null
      done | column -t -s $'\t'
    }

    # Properties that give a container-isolated agent its own root filesystem
    # (an empty read-only tmpfs; only the Nix store, the system profile, the
    # TLS roots, a minimal passwd/group and the workspace/home are mounted), its
    # own PID, IPC and hostname namespaces, and its own network namespace on
    # the agent bridge. The namespace and its /etc files are made by
    # `agentos-netns setup` from the unit's ExecStartPre and removed again by
    # ExecStopPost. Reads $gpu_devices from cmd_spawn; fills CONTAINER_PROPS.
    CONTAINER_PROPS=()
    container_props() {
      local id="$1" workspace="$2" gpu="$3"
      local netdir="/run/agentos/net/$id" ro=() rw=() p src d
      ro+=(/nix/store
        "$netdir/resolv.conf:/etc/resolv.conf" "$netdir/hosts:/etc/hosts"
        "$netdir/nsswitch.conf:/etc/nsswitch.conf"
        "$netdir/passwd:/etc/passwd" "$netdir/group:/etc/group")
      # NixOS paths are symlink chains into the store: mount what they resolve
      # to, and only the /etc files a tool needs (not the whole of /etc/static)
      local links=(/run/current-system/sw /etc/gitconfig /bin/sh /usr/bin/env
        /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt)
      if [ -n "$gpu" ]; then
        links+=(/run/opengl-driver)
      fi
      for p in "''${links[@]}"; do
        if src=$(readlink -f "$p") && [ -e "$src" ]; then
          ro+=("$src:$p")
        fi
      done
      rw+=("$workspace" "$AGENT_HOME")
      for d in "''${gpu_devices[@]}"; do
        rw+=("$d")
      done
      CONTAINER_PROPS=(
        -p RootDirectory=/var/empty
        -p TemporaryFileSystem=/:ro
        -p MountAPIVFS=yes
        -p PrivateDevices=yes
        -p PrivatePIDs=yes
        -p PrivateIPC=yes
        -p ProtectHostname=yes
        -p "NetworkNamespacePath=/run/netns/agentos-$id"
        -p "BindReadOnlyPaths=''${ro[*]}"
        -p "BindPaths=''${rw[*]}"
        -p "ExecStartPre=+$NETNS_HELPER setup $id"
        -p "ExecStopPost=+$NETNS_HELPER teardown $id"
        --setenv=SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
        --setenv=NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
      )
    }

    # ── pullrun isolation (experimental) ──────────────────────────────
    # Runs the agent in a Pullrun runc container (docs/pullrun.md). The
    # Pullrun daemon starts the container as root with a default capability
    # set and no user namespace, so the agent is started through setpriv, which
    # drops to the agent user's uid/gid, all capabilities and no_new_privs
    # before it runs. The container's stdout/stderr is discarded by Pullrun
    # and there is no stdin, so the output goes to a file that is mounted in
    # and followed here. This process stays alive for as long as the container
    # does: the agent daemon tracks it by pid, and `agentos kill` stops it.
    #
    # pullrun takes --cmd and -e as comma-separated lists; quote for that
    pr_q() { local x="''${1//\"/\"\"}"; printf '"%s"' "$x"; }

    # Usage: spawn_pullrun <id> <workspace> <agent-command> <KEY=VALUE>... -- <agent args>
    spawn_pullrun() {
      local id="$1" workspace="$2" cmd_path="$3"
      shift 3
      local envs=()
      while [ $# -gt 0 ] && [ "$1" != "--" ]; do
        envs+=("$1"); shift
      done
      shift
      local pr=("$PULLRUN_BIN" --direct=false --socket "$PULLRUN_SOCKET")

      # Only the Nix store and the system profile are mounted into the container
      [[ "$cmd_path" =~ ^(/nix/store|/run/current-system)/[^[:space:],:]+$ ]] || die "$cmd_path is not under /nix/store or /run/current-system, which are the only host paths a pullrun container sees"
      [[ "$workspace" != *:* && "$AGENT_HOME" != *:* ]] || die "workspace and home paths may not contain ':' with --isolation pullrun"
      [ -S "$PULLRUN_SOCKET" ] || die "the Pullrun daemon is not running (no $PULLRUN_SOCKET; systemctl status pullrun-runtime)"
      [ -w "$PULLRUN_SOCKET" ] || die "no access to $PULLRUN_SOCKET: --isolation pullrun needs membership in the agentos group"
      local digest
      digest=$("''${pr[@]}" images --json | jq -r --arg ref "$PULLRUN_IMAGE" '[.[]? | select(.image_ref == $ref)][0].root_digest // empty') \
        || die "could not list Pullrun images"
      [ -n "$digest" ] || die "image $PULLRUN_IMAGE is not in the Pullrun store (systemctl status pullrun-agent-image)"

      local uid gid out pw grp
      uid=$(id -u "$AGENT_USER")
      gid=$(id -g "$AGENT_USER")
      out="''${PULLRUN_LOG_DIR:?}/$id.log"
      pw="''${PULLRUN_LOG_DIR:?}/$id.passwd"
      grp="''${PULLRUN_LOG_DIR:?}/$id.group"
      (umask 007; : > "$out") 2>/dev/null || die "cannot write to $PULLRUN_LOG_DIR (membership in the agentos group needed)"
      (umask 022
        printf 'root:x:0:0:root:/root:/bin/sh\n%s:x:%s:%s::%s:/bin/sh\n' "$AGENT_USER" "$uid" "$gid" "$AGENT_HOME" > "$pw"
        printf 'root:x:0:\n%s:x:%s:\n' "$AGENT_USER" "$gid" > "$grp")

      # Read-only: the Nix store and the files the agent's tools expect. NixOS
      # paths are symlink chains into the store; mount what they resolve to.
      local mounts=(-v /nix/store:/nix/store:ro
        -v "$pw:/etc/passwd:ro" -v "$grp:/etc/group:ro"
        -v "$out:/run/agentos-agent.log")
      local p src
      for p in /run/current-system/sw /etc/gitconfig /bin/sh /usr/bin/env \
               /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt; do
        if src=$(readlink -f "$p") && [ -e "$src" ]; then
          mounts+=(-v "$src:$p:ro")
        fi
      done
      mounts+=(-v "$workspace:$workspace" -v "$AGENT_HOME:$AGENT_HOME")

      local envargs=() e
      for e in "''${envs[@]}" "HOME=$AGENT_HOME" "USER=$AGENT_USER" "PATH=/run/current-system/sw/bin" \
               "TERM=''${TERM:-xterm-256color}" "LANG=''${LANG:-C.UTF-8}" \
               SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt; do
        envargs+=(-e "$(pr_q "$e")")
      done

      # Runs as root inside the container until setpriv: send output to the
      # file, enter the workspace, drop privileges, run the agent
      # shellcheck disable=SC2016 # expanded by the shell in the container
      local script='exec >>/run/agentos-agent.log 2>&1; cd "$1" || exit 1; sp=$2; uid=$3; gid=$4; shift 4
    exec "$sp" --reuid="$uid" --regid="$gid" --clear-groups --no-new-privs --bounding-set -all -- "$@"'
      local cmdargs=() a
      for a in "$BASH" -c "$script" agentos-pullrun "$workspace" "$(command -v setpriv)" "$uid" "$gid" "$cmd_path" "$@"; do
        cmdargs+=(--cmd "$(pr_q "$a")")
      done

      local ncpu mem cpu
      ncpu=$(nproc)
      mem=$(conf '.limits.memory_mb // 4096')
      cpu=$(conf '.limits.cpu_percent // 100')

      warn "pullrun isolation is experimental: no stdin or TTY; output goes to $out"
      local tail_pid run_pid rc=0
      tail -n +1 -F "$out" 2>/dev/null &
      tail_pid=$!
      pr_stop() { "''${pr[@]}" stop "$id" >/dev/null 2>&1 || true; }
      trap pr_stop INT TERM
      "''${pr[@]}" run "sha256:$digest" --backend container --name "$id" --net bridge \
        --cpu "$((cpu * ncpu * 10))" --memory "$((mem * 1024 * 1024))" \
        "''${mounts[@]}" "''${envargs[@]}" "''${cmdargs[@]}" -a &
      run_pid=$!
      while kill -0 "$run_pid" 2>/dev/null; do
        wait "$run_pid" || rc=$?
      done
      sleep 1
      kill "$tail_pid" 2>/dev/null || true
      pr_stop
      rm -f "''${pw:?}" "''${grp:?}"
      exit "$rc"
    }

    # Kernel-surface hardening shared by sandbox and container units (keep in
    # step with HARDEN_PROPS in taskrunner.py). Deliberately absent:
    #  - MemoryDenyWriteExecute: Node/V8 needs W^X JIT pages.
    #  - ProcSubset=pid: hides /proc/{cpuinfo,meminfo,stat}; Node's os.cpus()
    #    then returns [] and jest/npm/webpack size their worker pools from it.
    # RestrictNamespaces=yes also stops agents from nesting bwrap or Chromium's
    # user-namespace sandbox (run Chromium with --no-sandbox in here).
    # Denied syscalls fail with EPERM rather than killing the process, so
    # libuv falls back from io_uring etc.
    HARDEN_PROPS=(
      -p SystemCallFilter=@system-service
      -p "SystemCallFilter=~@privileged @mount @module @raw-io @reboot @swap @obsolete @cpu-emulation @debug"
      -p SystemCallErrorNumber=EPERM
      -p SystemCallArchitectures=native
      -p RestrictNamespaces=yes
      -p "RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK"
      -p ProtectProc=invisible
      -p LockPersonality=yes
      -p RestrictRealtime=yes
      -p RestrictSUIDSGID=yes
      -p ProtectClock=yes
      -p ProtectControlGroups=yes
      -p ProtectKernelLogs=yes
      -p ProtectHostname=yes
      -p CapabilityBoundingSet=
      -p AmbientCapabilities=
      -p MemorySwapMax=0
    )

    # ── spawn ─────────────────────────────────────────────────────────
    cmd_spawn() {
      local agent="''${1:-}"
      [ -n "$agent" ] || die "Usage: agentos spawn <agent> [--workspace <name|path>] [--budget <usd>] [--model <m>] [--isolation <sandbox|container|pullrun>] [--gpu [N|any]] [--unsandboxed] [-- args]"
      shift
      local workspace="$PWD" model="" budget="" unsandboxed=0 isolation="" gpu=""
      local extra=()
      while [ $# -gt 0 ]; do
        case "$1" in
          --workspace) workspace="''${2:?--workspace needs a value}"; shift 2 ;;
          --model) model="''${2:?--model needs a value}"; shift 2 ;;
          --budget) budget="''${2:?--budget needs a value}"; shift 2 ;;
          --isolation) isolation="''${2:?--isolation needs a value}"; shift 2 ;;
          --gpu)
            if [ $# -ge 2 ] && [[ "$2" =~ ^(any|[0-9]+(,[0-9]+)*)$ ]]; then
              gpu="$2"; shift 2
            else
              gpu=any; shift
            fi ;;
          --unsandboxed) unsandboxed=1; shift ;;
          --) shift; extra+=("$@"); break ;;
          *) extra+=("$1"); shift ;;
        esac
      done

      local command cmd_path
      command=$(jq -r --arg a "$agent" '.agents[$a] // empty' "$RUNTIME")
      if [ -n "$command" ]; then
        cmd_path=$(command -v "$command") || die "$command is not installed"
      else
        cmd_path=$(extension_agent "$agent")
        [ -n "$cmd_path" ] || die "Unknown agent: $agent (see: agentos agents)"
        command="$cmd_path"
      fi

      # A bare name refers to a workspace under the workspace root
      if [[ "$workspace" != */* ]] && [ -d "$WORKSPACE_ROOT/$workspace" ]; then
        workspace="$WORKSPACE_ROOT/$workspace"
      fi
      [ -d "$workspace" ] || die "No such workspace: $workspace"
      workspace=$(realpath "$workspace")

      case "$isolation" in
        ""|sandbox|container|pullrun) ;;
        microvm) die "--isolation microvm is not supported yet: Firecracker has no host mounts in Pullrun, so the workspace cannot be shared with the VM (use --isolation container, or --isolation pullrun)" ;;
        *) die "unknown isolation mode: $isolation (use sandbox, container or pullrun)" ;;
      esac
      if [ "$unsandboxed" -eq 1 ]; then
        [ "$isolation" != container ] || die "--isolation container conflicts with --unsandboxed"
        [ "$isolation" != pullrun ] || die "--isolation pullrun conflicts with --unsandboxed"
        [ -z "$gpu" ] || die "--gpu needs a sandboxed agent (the GPU grant is enforced by its unit)"
        isolation=none
      else
        isolation="''${isolation:-$DEFAULT_ISOLATION}"
      fi
      if [ "$isolation" = container ]; then
        [ "$CONTAINER_ENABLED" = "true" ] || die "--isolation container needs agentos.networking.enable (agent bridge and gateway)"
        [ -n "$NETNS_HELPER" ] || die "runtime.json has no container helper"
      fi

      if [ "$isolation" = pullrun ]; then
        [ -z "$gpu" ] || die "--gpu is not supported with --isolation pullrun"
        [ "$PULLRUN_ENABLED" = "true" ] || die "--isolation pullrun needs agentos.pullrun.agentContainers.enable"
        [ -n "$PULLRUN_BIN" ] && [ -n "$PULLRUN_SOCKET" ] && [ -n "$PULLRUN_LOG_DIR" ] || die "runtime.json has no pullrun settings"
      fi

      local sandboxed=0
      if [ "$unsandboxed" -eq 0 ]; then
        case "$workspace" in
          "$WORKSPACE_ROOT"/?*) sandboxed=1 ;;
          *) die "$workspace is outside $WORKSPACE_ROOT, which the sandboxed agent user cannot write.
      Create a workspace:  agentos workspace create <name> --from $workspace
      or run as yourself:  agentos spawn $agent --unsandboxed" ;;
        esac
        # Pullrun mode talks to its own daemon and needs no sudo
        [ "$isolation" = pullrun ] || need_sudo
      fi

      local max running
      max=$(conf .max_agents)
      running=$(running_count)
      [ "$running" -lt "$max" ] || die "$running agents already running (limit $max)"

      local id
      id="$agent-$(date +%Y%m%d-%H%M%S)-$(printf '%04x' "$RANDOM")"
      valid_name "$id" || die "invalid agent name: $agent"

      # A fresh branch per agent session
      if ! git -C "$workspace" rev-parse --git-dir >/dev/null 2>&1; then
        git -C "$workspace" init --quiet
        info "Initialized git repository in $workspace"
      fi
      local branch="agent/$id"
      if ! git -C "$workspace" checkout --quiet -b "$branch" 2>/dev/null; then
        warn "could not create branch $branch; staying on the current branch"
        branch=$(git -C "$workspace" branch --show-current 2>/dev/null || true)
      fi

      # Environment for the agent
      local env=(
        "AGENTOS_AGENT_ID=$id"
        "AGENTOS_WORKSPACE=$workspace"
        "AGENTOS_BRANCH=$branch"
      )
      if [ -n "$model" ]; then
        env+=("AGENTOS_MODEL=$model")
      fi
      if [ "$GATEWAY_ENABLED" = "true" ]; then
        local health agent_gateway="$GATEWAY"
        health=$(curl -fsS -m 5 "$GATEWAY/_agentos/health") || die "model gateway is not responding at $GATEWAY"
        # A container cannot see the host's loopback; it uses the bridge address
        if [ "$isolation" = container ]; then
          agent_gateway="$CONTAINER_GATEWAY"
        fi
        # A Pullrun container sits on the pullrun-br0 bridge
        if [ "$isolation" = pullrun ]; then
          [ -n "$PULLRUN_GATEWAY" ] || die "runtime.json has no pullrun gateway address"
          agent_gateway="$PULLRUN_GATEWAY"
        fi
        # The gateway only answers agents presenting the token registered
        # here, so an agent cannot use another agent's id or budget
        [ -w "$ADMIN_SOCKET" ] || die "spawning through the gateway needs membership in the agentos group"
        local token
        token=$(od -An -N32 -tx1 /dev/urandom | tr -d ' \n')
        admin_api PUT "agents/$id" \
          "$(jq -cn --arg h "$(printf '%s' "$token" | sha256sum | cut -d' ' -f1)" '{token_sha256: $h}')" >/dev/null \
          || die "could not register $id with the model gateway"
        env+=(
          "ANTHROPIC_BASE_URL=$agent_gateway/agent/$id:$token/anthropic"
          "OPENAI_BASE_URL=$agent_gateway/agent/$id:$token/openai/v1"
        )
        local provider keyvar
        for provider in anthropic openai; do
          keyvar="''${provider^^}_API_KEY"
          if [ "$(echo "$health" | jq -r --arg p "$provider" '.providers[$p].managed_key // false')" = "true" ]; then
            env+=("$keyvar=agentos-managed")
          elif [ -n "''${!keyvar:-}" ]; then
            env+=("$keyvar=''${!keyvar}")
          fi
        done
        if [ -n "$budget" ]; then
          [ -w "$ADMIN_SOCKET" ] || die "--budget needs membership in the agentos group"
          admin_api PUT "budget/$id" "$(jq -cn --argjson usd "$budget" '{daily_usd: $usd}')" >/dev/null
        fi
      elif [ -n "$budget" ]; then
        die "--budget needs the model gateway (agentos.networking.enable)"
      elif [ "$isolation" = pullrun ]; then
        die "--isolation pullrun needs the model gateway (agentos.networking.enable)"
      fi
      # Other provider credentials pass through, unmetered
      local var
      for var in GEMINI_API_KEY GOOGLE_API_KEY DASHSCOPE_API_KEY FACTORY_API_KEY GITHUB_TOKEN GH_TOKEN; do
        if [ -n "''${!var:-}" ]; then
          env+=("$var=''${!var}")
        fi
      done

      # Reserve GPUs (exclusive; released when the agent's unit stops)
      local gpu_devices=() gpu_indexes="[]"
      if [ -n "$gpu" ]; then
        [ -n "$GPU_HELPER" ] || die "runtime.json has no GPU helper"
        local grant e
        grant=$(sudo -n "$GPU_HELPER" alloc "$id" "$gpu") || die "could not reserve a GPU (see: agentos gpu)"
        while IFS= read -r e; do
          env+=("$e")
        done < <(echo "$grant" | jq -r '.env | to_entries[] | "\(.key)=\(.value)"')
        env+=("LD_LIBRARY_PATH=/run/opengl-driver/lib")
        while IFS= read -r e; do
          gpu_devices+=("$e")
        done < <(echo "$grant" | jq -r '.devices[]')
        gpu_indexes=$(echo "$grant" | jq -c '[.gpus[].index]')
        info "Reserved GPU $(echo "$gpu_indexes" | jq -r 'join(",")')"
      fi

      # Register with the daemon
      local unit="" user
      user=$(id -un)
      if [ "$sandboxed" -eq 1 ]; then
        unit="agentos-agent-$id.service"
        user="$AGENT_USER"
      fi
      # Pullrun mode has no systemd unit: the daemon tracks this process
      if [ "$isolation" = pullrun ]; then
        unit=""
      fi
      (umask 002; jq -n \
        --arg id "$id" --arg agent "$agent" --arg command "$command" \
        --arg workspace "$workspace" --arg branch "$branch" --arg user "$user" \
        --arg unit "$unit" --arg operator "$(id -un)" --argjson pid "$$" \
        --argjson sandboxed "$sandboxed" --argjson started "$(date +%s)" \
        --arg isolation "$isolation" --argjson gpus "$gpu_indexes" \
        '{id: $id, agent: $agent, command: $command, workspace: $workspace,
          branch: $branch, user: $user, operator: $operator, pid: $pid,
          sandboxed: ($sandboxed == 1), isolation: $isolation, gpus: $gpus,
          started_at: $started, status: "running"}
         + (if $unit != "" then {unit: $unit} else {} end)' \
        > "$(state_file "$id")")

      ok "Starting $agent as $id"
      info "Workspace: $workspace (branch $branch), isolation: $isolation"

      if [ "$isolation" = pullrun ]; then
        spawn_pullrun "$id" "$workspace" "$cmd_path" "''${env[@]}" -- "''${extra[@]}"
      elif [ "$sandboxed" -eq 1 ]; then
        local ncpu mem cpu tasks
        ncpu=$(nproc)
        mem=$(conf '.limits.memory_mb // 4096')
        cpu=$(conf '.limits.cpu_percent // 100')
        tasks=$(conf '.limits.tasks_max // 1024')
        local props=(
          -p "MemoryMax=''${mem}M"
          -p "CPUQuota=$((cpu * ncpu))%"
          -p "TasksMax=$tasks"
          -p NoNewPrivileges=yes
          -p PrivateTmp=yes
          -p ProtectSystem=strict
          -p ProtectHome=yes
          -p "ReadWritePaths=$workspace $AGENT_HOME"
          -p ProtectKernelTunables=yes
          -p ProtectKernelModules=yes
          -p UMask=0002
          "''${HARDEN_PROPS[@]}"
          --setenv="HOME=$AGENT_HOME"
          --setenv="USER=$AGENT_USER"
          --setenv="PATH=/run/current-system/sw/bin"
          --setenv="TERM=''${TERM:-xterm-256color}"
          --setenv="LANG=''${LANG:-C.UTF-8}"
        )
        local e
        for e in "''${env[@]}"; do
          props+=(--setenv="$e")
        done
        if [ "$isolation" = container ]; then
          container_props "$id" "$workspace" "$gpu"
          props+=("''${CONTAINER_PROPS[@]}")
        fi
        if [ "$GPU_ENABLED" = "true" ]; then
          # Only the GPUs granted below stay reachable
          props+=(-p DevicePolicy=closed)
        fi
        if [ -n "$gpu" ]; then
          local d g
          for d in "''${gpu_devices[@]}"; do
            props+=(-p "DeviceAllow=$d rw")
          done
          for g in render video; do
            if getent group "$g" >/dev/null; then
              props+=(-p "SupplementaryGroups=$g")
            fi
          done
          props+=(-p "ExecStopPost=+$GPU_HELPER release $id")
        fi
        local io=--pipe
        if [ -t 0 ] && [ -t 1 ]; then
          io=--pty
        fi
        local run=(sudo -n systemd-run --quiet --collect --wait "$io"
          --unit="agentos-agent-$id"
          --uid="$AGENT_USER" --gid="$AGENT_USER"
          --working-directory="$workspace"
          "''${props[@]}"
          -- "$cmd_path" "''${extra[@]}")
        if [ -z "$gpu" ]; then
          exec "''${run[@]}"
        fi
        # The unit releases the GPU when it stops; if it never started, do it here
        local rc=0
        "''${run[@]}" || rc=$?
        sudo -n "$GPU_HELPER" release "$id" || true
        exit "$rc"
      else
        warn "running unsandboxed as $(id -un): no resource limits, and the agent can bypass the gateway"
        cd "$workspace"
        exec env "''${env[@]}" "$cmd_path" "''${extra[@]}"
      fi
    }

    # ── list / logs / kill / shell ────────────────────────────────────
    cmd_list() {
      local spend="{}"
      if [ "$GATEWAY_ENABLED" = "true" ]; then
        spend=$(curl -fsS -m 5 "$GATEWAY/_agentos/spend" 2>/dev/null || echo "{}")
      fi
      local files=() f
      for f in "$STATE_DIR"/*.json; do
        if [ -e "$f" ]; then files+=("$f"); fi
      done
      while IFS= read -r f; do
        files+=("$f")
      done < <(find "$STATE_DIR/history" -maxdepth 1 -name '*.json' -printf '%T@ %p\n' 2>/dev/null | sort -rn | head -n 10 | cut -d' ' -f2-)
      if [ "''${#files[@]}" -eq 0 ]; then
        echo "No agents yet. Start one with: agentos spawn <agent>"
        return
      fi
      jq -rs --argjson spend "$spend" '
        (["ID", "STATUS", "SPENT TODAY", "ISOLATION", "WORKSPACE"] | @tsv),
        (.[] | [ .id, .status + (if .reason then " (" + .reason + ")" else "" end),
                 "$" + ((($spend.agents // {})[.id].usd // 0) * 10000 | round / 10000 | tostring),
                 (.isolation // (if .sandboxed then "sandbox" else "none" end))
                   + (if (.gpus // []) | length > 0 then " gpu:" + (.gpus | map(tostring) | join(",")) else "" end),
                 .workspace ] | @tsv)' "''${files[@]}" | column -t -s $'\t'
    }

    find_state() {
      local id="$1"
      valid_name "$id" || die "invalid agent id: $id"
      if [ -f "$(state_file "$id")" ]; then
        state_file "$id"
      elif [ -f "$STATE_DIR/history/$id.json" ]; then
        echo "$STATE_DIR/history/$id.json"
      else
        die "Agent not found: $id"
      fi
    }

    cmd_logs() {
      local id="''${1:-}" follow="''${2:-}"
      [ -n "$id" ] || die "Usage: agentos logs <agent-id> [-f]"
      find_state "$id" >/dev/null
      local log="$LOG_DIR/$id.log"
      local fmt='[(.ts | floor | strftime("%H:%M:%S")), .status, (.model // "-"), (if .usage then "in=\(.usage.input_tokens) out=\(.usage.output_tokens) cache_read=\(.usage.cache_read_tokens)" else (.error // "-") end), (if .cost_usd then "$\(.cost_usd)" else "-" end)] | @tsv'
      if [ "$follow" = "-f" ]; then
        tail -n 20 -F "$log" 2>/dev/null | jq --unbuffered -r "$fmt"
      elif [ -f "$log" ]; then
        jq -r "$fmt" "$log" | column -t -s $'\t'
      else
        info "No model API calls recorded for $id"
      fi
    }

    cmd_kill() {
      local id="''${1:-}"
      [ -n "$id" ] || die "Usage: agentos kill <agent-id>"
      local f
      f=$(find_state "$id")
      [ "$(jq -r .status "$f")" = "running" ] || die "Agent $id is not running"
      local unit pid
      unit=$(jq -r '.unit // empty' "$f")
      pid=$(jq -r '.pid // empty' "$f")
      if [ -n "$unit" ]; then
        need_sudo
        sudo -n systemctl stop "$unit" || true
      elif [ -n "$pid" ]; then
        kill "$pid" 2>/dev/null || die "could not signal pid $pid"
      fi
      local tmp
      tmp=$(mktemp "$STATE_DIR/.$id.XXXXXX")
      jq --argjson t "$(date +%s)" '.status = "killed" | .reason = "stopped by operator" | .ended_at = $t' "$f" > "$tmp"
      chmod 664 "$tmp"
      mv "$tmp" "$f"
      ok "Stopped $id"
    }

    cmd_shell() {
      local id="''${1:-}"
      [ -n "$id" ] || die "Usage: agentos shell <agent-id>"
      local f unit workspace
      f=$(find_state "$id")
      unit=$(jq -r '.unit // empty' "$f")
      workspace=$(jq -r .workspace "$f")
      if [ "$(jq -r '.isolation // "sandbox"' "$f")" = pullrun ]; then
        [ -n "$PULLRUN_BIN" ] || die "runtime.json has no pullrun settings"
        # A shell as root inside the container (not as the agent user)
        exec "$PULLRUN_BIN" --direct=false --socket "$PULLRUN_SOCKET" exec "$id" -- /run/current-system/sw/bin/bash
      fi
      if [ -z "$unit" ]; then
        cd "$workspace"
        exec "''${SHELL:-bash}"
      fi
      need_sudo
      local pid
      pid=$(sudo -n systemctl show -p MainPID --value "$unit")
      [ "''${pid:-0}" -gt 0 ] || die "$unit is not running"
      local ns=(-m)
      if [ "$(jq -r '.isolation // "sandbox"' "$f")" = container ]; then
        # Enter the container's own mount, network, PID, IPC and UTS namespaces.
        # With PrivatePIDs the unit's main process may be outside the PID
        # namespace, so use a process of the unit that is inside it.
        local cg inner
        cg=$(sudo -n systemctl show -p ControlGroup --value "$unit")
        inner=$(sudo -n sh -c 'host=$(readlink /proc/self/ns/pid)
          for p in $(cat "/sys/fs/cgroup$1/cgroup.procs"); do
            if [ "$(readlink "/proc/$p/ns/pid")" != "$host" ]; then echo "$p"; exit 0; fi
          done' sh "$cg" || true)
        pid="''${inner:-$pid}"
        ns=(-m -n -p -i -u)
      fi
      exec sudo -n nsenter -t "$pid" "''${ns[@]}" -S "$(id -u "$AGENT_USER")" -G "$(id -g "$AGENT_USER")" \
        --wd="$workspace" -- env HOME="$AGENT_HOME" PATH=/run/current-system/sw/bin bash
    }

    cmd_gpu() {
      [ -n "$GPU_HELPER" ] || die "runtime.json has no GPU helper"
      if [ "$GPU_ENABLED" != "true" ]; then
        info "GPU scheduling is off (agentos.gpu.enable); showing detected devices only"
      fi
      "$GPU_HELPER" list "$@"
    }

    cmd_status() {
      echo -e "''${BOLD}AgentOS $VERSION''${NC}"
      local svc
      for svc in agentos-daemon agentos-model-gateway redis-agentos; do
        if systemctl is-active --quiet "$svc"; then
          echo -e "  ''${GREEN}running''${NC}  $svc"
        else
          echo -e "  ''${RED}$(systemctl is-active "$svc" 2>/dev/null || true)''${NC}  $svc"
        fi
      done
      echo "  Agents running: $(running_count) of $(conf .max_agents)"
      if [ "$GATEWAY_ENABLED" = "true" ]; then
        curl -fsS -m 5 "$GATEWAY/_agentos/spend" 2>/dev/null \
          | jq -r '"  Spend today:    $\(.global_usd * 100 | round / 100) of $\(.global_limit_usd)"' || true
      fi
      echo "  Load:           $(cut -d' ' -f1-3 /proc/loadavg)"
      echo "  Memory free:    $(free -m | awk '/^Mem:/ {print $7 " MB of " $2 " MB"}')"
      echo "  Disk free:      $(df -h "$WORKSPACE_ROOT" | awk 'NR==2 {print $4 " of " $2}')"
    }

    # ── workspaces & snapshots ────────────────────────────────────────
    cmd_workspace() {
      local sub="''${1:-list}"
      shift || true
      case "$sub" in
        create)
          local name="''${1:-}" from=""
          [ -n "$name" ] || die "Usage: agentos workspace create <name> [--from <git-url|path>]"
          shift
          if [ "''${1:-}" = "--from" ]; then
            from="''${2:?--from needs a value}"
          fi
          valid_name "$name" || die "invalid workspace name: $name"
          local path="$WORKSPACE_ROOT/$name"
          [ ! -e "$path" ] || die "$path already exists"
          if [ -n "$from" ]; then
            git clone --quiet "$from" "$path"
          else
            mkdir "$path"
            git -C "$path" init --quiet
            # A root commit, so agent branches are real refs to diff against
            git -C "$path" -c user.name=AgentOS -c user.email=agentos@localhost \
              commit --quiet --allow-empty -m "Initialize workspace $name"
          fi
          chmod -R g+rwX "$path"
          ok "Created workspace $path"
          ;;
        list|ls)
          ls -1 "$WORKSPACE_ROOT" 2>/dev/null || true
          ;;
        rm)
          local name="''${1:-}"
          valid_name "$name" || die "Usage: agentos workspace rm <name>"
          [ -d "$WORKSPACE_ROOT/$name" ] || die "No such workspace: $name"
          # Files created by agents belong to agentos-agent
          if ! rm -rf "''${WORKSPACE_ROOT:?}/$name" 2>/dev/null; then
            need_sudo
            sudo -n rm -rf "''${WORKSPACE_ROOT:?}/$name"
          fi
          ok "Removed workspace $name"
          ;;
        *) die "Usage: agentos workspace <create|list|rm>" ;;
      esac
    }

    cmd_snapshot() {
      local name="''${1:-manual-$(date +%Y%m%d-%H%M%S)}"
      valid_name "$name" || die "invalid snapshot name: $name"
      need_sudo
      sudo -n btrfs subvolume snapshot -r "$WORKSPACE_ROOT" "$SNAPSHOT_DIR/$name" >/dev/null \
        || die "snapshot failed (is $WORKSPACE_ROOT a btrfs subvolume?)"
      ok "Snapshot $SNAPSHOT_DIR/$name"
    }

    cmd_snapshots() { ls -1 "$SNAPSHOT_DIR" 2>/dev/null || true; }

    cmd_rollback() {
      local snap="''${1:-}" ws="''${2:-}"
      { valid_name "$snap" && valid_name "$ws"; } || die "Usage: agentos rollback <snapshot> <workspace>"
      [ -d "$SNAPSHOT_DIR/$snap/$ws" ] || die "No workspace $ws in snapshot $snap"
      warn "This replaces $WORKSPACE_ROOT/$ws with its state in $snap"
      if [ -t 0 ]; then
        local answer
        read -rp "Continue? [y/N] " answer
        [ "$answer" = "y" ] || exit 0
      fi
      need_sudo
      sudo -n rsync -a --delete "$SNAPSHOT_DIR/$snap/$ws/" "$WORKSPACE_ROOT/$ws/"
      ok "Rolled back $ws to $snap"
    }

    # ── main ──────────────────────────────────────────────────────────
    main() {
      local cmd="''${1:-help}"
      shift || true
      case "$cmd" in
        agents)          cmd_agents ;;
        spawn|run)       cmd_spawn "$@" ;;
        list|ls)         cmd_list ;;
        logs)            cmd_logs "$@" ;;
        kill|stop)       cmd_kill "$@" ;;
        shell)           cmd_shell "$@" ;;
        gpu|gpus)        cmd_gpu "$@" ;;
        status|st)       cmd_status ;;
        workspace|ws)    cmd_workspace "$@" ;;
        snapshot)        cmd_snapshot "$@" ;;
        snapshots)       cmd_snapshots ;;
        rollback)        cmd_rollback "$@" ;;
        budget)          exec agentos-budget "$@" ;;
        install|i)
          [ -n "''${1:-}" ] || die "Usage: agentos install <package>"
          nix profile install "nixpkgs#$1" ;;
        search)
          [ -n "''${1:-}" ] || die "Usage: agentos search <query>"
          nix search nixpkgs "$1" ;;
        version|--version|-v) cmd_version ;;
        help|--help|-h)  cmd_help ;;
        *)               err "Unknown command: $cmd"; cmd_help; exit 1 ;;
      esac
    }

    main "$@"
  '';

  meta = {
    description = "AgentOS command-line interface";
    mainProgram = "agentos";
    license = lib.licenses.mit;
  };
}
