# AgentOS CLI — user-facing command for managing agents
#
# Configuration comes from /etc/agentos/runtime.json (generated by the
# runtime module); AGENTOS_RUNTIME overrides the path.
{ lib
, writeShellApplication
, coreutils
, curl
, gawk
, git
, gnugrep
, jq
, procps
, rsync
, util-linux
}:

writeShellApplication {
  name = "agentos";
  runtimeInputs = [ coreutils curl gawk git gnugrep jq procps rsync util-linux ];

  text = ''
    RUNTIME="''${AGENTOS_RUNTIME:-/etc/agentos/runtime.json}"
    VERSION="0.3.0"

    if [ -t 2 ]; then
      RED='\033[0;31m' GREEN='\033[0;32m' YELLOW='\033[1;33m' BLUE='\033[0;34m' BOLD='\033[1m' NC='\033[0m'
    else
      RED="" GREEN="" YELLOW="" BLUE="" BOLD="" NC=""
    fi
    info() { echo -e "''${BLUE}[INFO]''${NC} $*" >&2; }
    ok()   { echo -e "''${GREEN}[OK]''${NC} $*" >&2; }
    warn() { echo -e "''${YELLOW}[WARN]''${NC} $*" >&2; }
    err()  { echo -e "''${RED}[ERR]''${NC} $*" >&2; }
    die()  { err "$*"; exit 1; }

    [ -r "$RUNTIME" ] || die "$RUNTIME not found; is agentos.runtime enabled?"
    conf() { jq -r "$1" "$RUNTIME"; }
    WORKSPACE_ROOT=$(conf .workspace_root)
    STATE_DIR=$(conf .state_dir)
    LOG_DIR=$(conf .log_dir)
    AGENT_USER=$(conf .agent_user)
    AGENT_HOME=$(conf .agent_home)
    GATEWAY=$(conf .gateway_url)
    ADMIN_SOCKET=$(conf .admin_socket)
    GATEWAY_ENABLED=$(conf .gateway_enabled)
    SNAPSHOT_DIR=/var/lib/agentos/snapshots

    valid_name() { [[ "$1" =~ ^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$ ]]; }
    state_file() { echo "$STATE_DIR/$1.json"; }
    running_count() {
      local n=0 f
      for f in "$STATE_DIR"/*.json; do
        [ -e "$f" ] || continue
        if [ "$(jq -r .status "$f" 2>/dev/null)" = "running" ]; then
          n=$((n + 1))
        fi
      done
      echo "$n"
    }
    need_sudo() {
      sudo -n true 2>/dev/null || die "this needs passwordless sudo (agent units are started as root)"
    }
    admin_api() {
      local method="$1" path="$2"
      local args=(-fsS --unix-socket "$ADMIN_SOCKET" -X "$method" -H 'Content-Type: application/json')
      if [ $# -ge 3 ]; then
        args+=(--data "$3")
      fi
      curl "''${args[@]}" "http://localhost/_agentos/$path"
    }

    # ── help ──────────────────────────────────────────────────────────
    cmd_help() {
      cat <<'HELP'
    AgentOS — an OS for coding agents

    USAGE:
        agentos <COMMAND> [OPTIONS]

    AGENTS:
        agents                     List available agents
        spawn <agent> [options] [-- agent args]
            --workspace <name|path>  Workspace (default: current directory)
            --budget <usd>           Daily budget for this agent
            --model <name>           Exported as AGENTOS_MODEL
            --unsandboxed            Run as yourself instead of agentos-agent
        list                       Running and recent agents with today's spend
        logs <id> [-f]             Model API calls made by an agent
        kill <id>                  Stop an agent
        shell <id>                 Shell inside a running agent's sandbox
        status                     Service health and totals

    WORKSPACES:
        workspace create <name> [--from <git-url|path>]
        workspace list
        workspace rm <name>
        snapshot [name]            Snapshot all workspaces (btrfs)
        snapshots                  List snapshots
        rollback <snapshot> <workspace>

    OTHER:
        budget ...                 Same as agentos-budget
        install <pkg>              nix profile install nixpkgs#<pkg>
        search <query>             nix search nixpkgs <query>
        version | help
    HELP
    }

    cmd_version() { echo "AgentOS $VERSION"; }

    cmd_agents() {
      echo "Agents (agentos spawn <name>):"
      jq -r '.agents | to_entries | group_by(.value)[] | "  \(map(.key) | join(", "))\t-> \(.[0].value)"' "$RUNTIME" \
        | column -t -s $'\t'
    }

    # ── spawn ─────────────────────────────────────────────────────────
    cmd_spawn() {
      local agent="''${1:-}"
      [ -n "$agent" ] || die "Usage: agentos spawn <agent> [--workspace <name|path>] [--budget <usd>] [--model <m>] [--unsandboxed] [-- args]"
      shift
      local workspace="$PWD" model="" budget="" unsandboxed=0
      local extra=()
      while [ $# -gt 0 ]; do
        case "$1" in
          --workspace) workspace="''${2:?--workspace needs a value}"; shift 2 ;;
          --model) model="''${2:?--model needs a value}"; shift 2 ;;
          --budget) budget="''${2:?--budget needs a value}"; shift 2 ;;
          --unsandboxed) unsandboxed=1; shift ;;
          --) shift; extra+=("$@"); break ;;
          *) extra+=("$1"); shift ;;
        esac
      done

      local command cmd_path
      command=$(jq -r --arg a "$agent" '.agents[$a] // empty' "$RUNTIME")
      [ -n "$command" ] || die "Unknown agent: $agent (see: agentos agents)"
      cmd_path=$(command -v "$command") || die "$command is not installed"

      # A bare name refers to a workspace under the workspace root
      if [[ "$workspace" != */* ]] && [ -d "$WORKSPACE_ROOT/$workspace" ]; then
        workspace="$WORKSPACE_ROOT/$workspace"
      fi
      [ -d "$workspace" ] || die "No such workspace: $workspace"
      workspace=$(realpath "$workspace")

      local sandboxed=0
      if [ "$unsandboxed" -eq 0 ]; then
        case "$workspace" in
          "$WORKSPACE_ROOT"/?*) sandboxed=1 ;;
          *) die "$workspace is outside $WORKSPACE_ROOT, which the sandboxed agent user cannot write.
      Create a workspace:  agentos workspace create <name> --from $workspace
      or run as yourself:  agentos spawn $agent --unsandboxed" ;;
        esac
        need_sudo
      fi

      local max running
      max=$(conf .max_agents)
      running=$(running_count)
      [ "$running" -lt "$max" ] || die "$running agents already running (limit $max)"

      local id
      id="$agent-$(date +%Y%m%d-%H%M%S)-$(printf '%04x' "$RANDOM")"
      valid_name "$id" || die "invalid agent name: $agent"

      # A fresh branch per agent session
      if ! git -C "$workspace" rev-parse --git-dir >/dev/null 2>&1; then
        git -C "$workspace" init --quiet
        info "Initialized git repository in $workspace"
      fi
      local branch="agent/$id"
      if ! git -C "$workspace" checkout --quiet -b "$branch" 2>/dev/null; then
        warn "could not create branch $branch; staying on the current branch"
        branch=$(git -C "$workspace" branch --show-current 2>/dev/null || true)
      fi

      # Environment for the agent
      local env=(
        "AGENTOS_AGENT_ID=$id"
        "AGENTOS_WORKSPACE=$workspace"
        "AGENTOS_BRANCH=$branch"
      )
      if [ -n "$model" ]; then
        env+=("AGENTOS_MODEL=$model")
      fi
      if [ "$GATEWAY_ENABLED" = "true" ]; then
        local health
        health=$(curl -fsS -m 5 "$GATEWAY/_agentos/health") || die "model gateway is not responding at $GATEWAY"
        env+=(
          "ANTHROPIC_BASE_URL=$GATEWAY/agent/$id/anthropic"
          "OPENAI_BASE_URL=$GATEWAY/agent/$id/openai/v1"
        )
        local provider keyvar
        for provider in anthropic openai; do
          keyvar="''${provider^^}_API_KEY"
          if [ "$(echo "$health" | jq -r --arg p "$provider" '.providers[$p].managed_key // false')" = "true" ]; then
            env+=("$keyvar=agentos-managed")
          elif [ -n "''${!keyvar:-}" ]; then
            env+=("$keyvar=''${!keyvar}")
          fi
        done
        if [ -n "$budget" ]; then
          [ -w "$ADMIN_SOCKET" ] || die "--budget needs membership in the agentos group"
          admin_api PUT "budget/$id" "$(jq -cn --argjson usd "$budget" '{daily_usd: $usd}')" >/dev/null
        fi
      elif [ -n "$budget" ]; then
        die "--budget needs the model gateway (agentos.networking.enable)"
      fi
      # Other provider credentials pass through, unmetered
      local var
      for var in GEMINI_API_KEY GOOGLE_API_KEY DASHSCOPE_API_KEY FACTORY_API_KEY GITHUB_TOKEN GH_TOKEN; do
        if [ -n "''${!var:-}" ]; then
          env+=("$var=''${!var}")
        fi
      done

      # Register with the daemon
      local unit="" user
      user=$(id -un)
      if [ "$sandboxed" -eq 1 ]; then
        unit="agentos-agent-$id.service"
        user="$AGENT_USER"
      fi
      (umask 002; jq -n \
        --arg id "$id" --arg agent "$agent" --arg command "$command" \
        --arg workspace "$workspace" --arg branch "$branch" --arg user "$user" \
        --arg unit "$unit" --arg operator "$(id -un)" --argjson pid "$$" \
        --argjson sandboxed "$sandboxed" --argjson started "$(date +%s)" \
        '{id: $id, agent: $agent, command: $command, workspace: $workspace,
          branch: $branch, user: $user, operator: $operator, pid: $pid,
          sandboxed: ($sandboxed == 1), started_at: $started, status: "running"}
         + (if $unit != "" then {unit: $unit} else {} end)' \
        > "$(state_file "$id")")

      ok "Starting $agent as $id"
      info "Workspace: $workspace (branch $branch)"

      if [ "$sandboxed" -eq 1 ]; then
        local ncpu mem cpu tasks
        ncpu=$(nproc)
        mem=$(conf '.limits.memory_mb // 4096')
        cpu=$(conf '.limits.cpu_percent // 100')
        tasks=$(conf '.limits.tasks_max // 1024')
        local props=(
          -p "MemoryMax=''${mem}M"
          -p "CPUQuota=$((cpu * ncpu))%"
          -p "TasksMax=$tasks"
          -p NoNewPrivileges=yes
          -p PrivateTmp=yes
          -p ProtectSystem=strict
          -p ProtectHome=yes
          -p "ReadWritePaths=$workspace $AGENT_HOME"
          -p ProtectKernelTunables=yes
          -p ProtectKernelModules=yes
          -p ProtectControlGroups=yes
          -p RestrictSUIDSGID=yes
          -p LockPersonality=yes
          -p UMask=0002
          --setenv="HOME=$AGENT_HOME"
          --setenv="USER=$AGENT_USER"
          --setenv="PATH=/run/current-system/sw/bin"
          --setenv="TERM=''${TERM:-xterm-256color}"
          --setenv="LANG=''${LANG:-C.UTF-8}"
        )
        local e
        for e in "''${env[@]}"; do
          props+=(--setenv="$e")
        done
        local io=--pipe
        if [ -t 0 ] && [ -t 1 ]; then
          io=--pty
        fi
        exec sudo -n systemd-run --quiet --collect --wait "$io" \
          --unit="agentos-agent-$id" \
          --uid="$AGENT_USER" --gid="$AGENT_USER" \
          --working-directory="$workspace" \
          "''${props[@]}" \
          -- "$cmd_path" "''${extra[@]}"
      else
        warn "running unsandboxed as $(id -un): no resource limits, and the agent can bypass the gateway"
        cd "$workspace"
        exec env "''${env[@]}" "$cmd_path" "''${extra[@]}"
      fi
    }

    # ── list / logs / kill / shell ────────────────────────────────────
    cmd_list() {
      local spend="{}"
      if [ "$GATEWAY_ENABLED" = "true" ]; then
        spend=$(curl -fsS -m 5 "$GATEWAY/_agentos/spend" 2>/dev/null || echo "{}")
      fi
      local files=() f
      for f in "$STATE_DIR"/*.json; do
        if [ -e "$f" ]; then files+=("$f"); fi
      done
      while IFS= read -r f; do
        files+=("$f")
      done < <(find "$STATE_DIR/history" -maxdepth 1 -name '*.json' -printf '%T@ %p\n' 2>/dev/null | sort -rn | head -n 10 | cut -d' ' -f2-)
      if [ "''${#files[@]}" -eq 0 ]; then
        echo "No agents yet. Start one with: agentos spawn <agent>"
        return
      fi
      jq -rs --argjson spend "$spend" '
        (["ID", "STATUS", "SPENT TODAY", "WORKSPACE"] | @tsv),
        (.[] | [ .id, .status + (if .reason then " (" + .reason + ")" else "" end),
                 "$" + ((($spend.agents // {})[.id].usd // 0) * 10000 | round / 10000 | tostring),
                 .workspace ] | @tsv)' "''${files[@]}" | column -t -s $'\t'
    }

    find_state() {
      local id="$1"
      valid_name "$id" || die "invalid agent id: $id"
      if [ -f "$(state_file "$id")" ]; then
        state_file "$id"
      elif [ -f "$STATE_DIR/history/$id.json" ]; then
        echo "$STATE_DIR/history/$id.json"
      else
        die "Agent not found: $id"
      fi
    }

    cmd_logs() {
      local id="''${1:-}" follow="''${2:-}"
      [ -n "$id" ] || die "Usage: agentos logs <agent-id> [-f]"
      find_state "$id" >/dev/null
      local log="$LOG_DIR/$id.log"
      local fmt='[(.ts | floor | strftime("%H:%M:%S")), .status, (.model // "-"), (if .usage then "in=\(.usage.input_tokens) out=\(.usage.output_tokens) cache_read=\(.usage.cache_read_tokens)" else (.error // "-") end), (if .cost_usd then "$\(.cost_usd)" else "-" end)] | @tsv'
      if [ "$follow" = "-f" ]; then
        tail -n 20 -F "$log" 2>/dev/null | jq --unbuffered -r "$fmt"
      elif [ -f "$log" ]; then
        jq -r "$fmt" "$log" | column -t -s $'\t'
      else
        info "No model API calls recorded for $id"
      fi
    }

    cmd_kill() {
      local id="''${1:-}"
      [ -n "$id" ] || die "Usage: agentos kill <agent-id>"
      local f
      f=$(find_state "$id")
      [ "$(jq -r .status "$f")" = "running" ] || die "Agent $id is not running"
      local unit pid
      unit=$(jq -r '.unit // empty' "$f")
      pid=$(jq -r '.pid // empty' "$f")
      if [ -n "$unit" ]; then
        need_sudo
        sudo -n systemctl stop "$unit" || true
      elif [ -n "$pid" ]; then
        kill "$pid" 2>/dev/null || die "could not signal pid $pid"
      fi
      local tmp
      tmp=$(mktemp "$STATE_DIR/.$id.XXXXXX")
      jq --argjson t "$(date +%s)" '.status = "killed" | .reason = "stopped by operator" | .ended_at = $t' "$f" > "$tmp"
      chmod 664 "$tmp"
      mv "$tmp" "$f"
      ok "Stopped $id"
    }

    cmd_shell() {
      local id="''${1:-}"
      [ -n "$id" ] || die "Usage: agentos shell <agent-id>"
      local f unit workspace
      f=$(find_state "$id")
      unit=$(jq -r '.unit // empty' "$f")
      workspace=$(jq -r .workspace "$f")
      if [ -z "$unit" ]; then
        cd "$workspace"
        exec "''${SHELL:-bash}"
      fi
      need_sudo
      local pid
      pid=$(sudo -n systemctl show -p MainPID --value "$unit")
      [ "''${pid:-0}" -gt 0 ] || die "$unit is not running"
      exec sudo -n nsenter -t "$pid" -m -S "$(id -u "$AGENT_USER")" -G "$(id -g "$AGENT_USER")" \
        --wd="$workspace" -- env HOME="$AGENT_HOME" PATH=/run/current-system/sw/bin bash
    }

    cmd_status() {
      echo -e "''${BOLD}AgentOS $VERSION''${NC}"
      local svc
      for svc in agentos-daemon agentos-model-gateway redis-agentos; do
        if systemctl is-active --quiet "$svc"; then
          echo -e "  ''${GREEN}running''${NC}  $svc"
        else
          echo -e "  ''${RED}$(systemctl is-active "$svc" 2>/dev/null || true)''${NC}  $svc"
        fi
      done
      echo "  Agents running: $(running_count) of $(conf .max_agents)"
      if [ "$GATEWAY_ENABLED" = "true" ]; then
        curl -fsS -m 5 "$GATEWAY/_agentos/spend" 2>/dev/null \
          | jq -r '"  Spend today:    $\(.global_usd * 100 | round / 100) of $\(.global_limit_usd)"' || true
      fi
      echo "  Load:           $(cut -d' ' -f1-3 /proc/loadavg)"
      echo "  Memory free:    $(free -m | awk '/^Mem:/ {print $7 " MB of " $2 " MB"}')"
      echo "  Disk free:      $(df -h "$WORKSPACE_ROOT" | awk 'NR==2 {print $4 " of " $2}')"
    }

    # ── workspaces & snapshots ────────────────────────────────────────
    cmd_workspace() {
      local sub="''${1:-list}"
      shift || true
      case "$sub" in
        create)
          local name="''${1:-}" from=""
          [ -n "$name" ] || die "Usage: agentos workspace create <name> [--from <git-url|path>]"
          shift
          if [ "''${1:-}" = "--from" ]; then
            from="''${2:?--from needs a value}"
          fi
          valid_name "$name" || die "invalid workspace name: $name"
          local path="$WORKSPACE_ROOT/$name"
          [ ! -e "$path" ] || die "$path already exists"
          if [ -n "$from" ]; then
            git clone --quiet "$from" "$path"
          else
            mkdir "$path"
            git -C "$path" init --quiet
            # A root commit, so agent branches are real refs to diff against
            git -C "$path" -c user.name=AgentOS -c user.email=agentos@localhost \
              commit --quiet --allow-empty -m "Initialize workspace $name"
          fi
          chmod -R g+rwX "$path"
          ok "Created workspace $path"
          ;;
        list|ls)
          ls -1 "$WORKSPACE_ROOT" 2>/dev/null || true
          ;;
        rm)
          local name="''${1:-}"
          valid_name "$name" || die "Usage: agentos workspace rm <name>"
          [ -d "$WORKSPACE_ROOT/$name" ] || die "No such workspace: $name"
          # Files created by agents belong to agentos-agent
          if ! rm -rf "''${WORKSPACE_ROOT:?}/$name" 2>/dev/null; then
            need_sudo
            sudo -n rm -rf "''${WORKSPACE_ROOT:?}/$name"
          fi
          ok "Removed workspace $name"
          ;;
        *) die "Usage: agentos workspace <create|list|rm>" ;;
      esac
    }

    cmd_snapshot() {
      local name="''${1:-manual-$(date +%Y%m%d-%H%M%S)}"
      valid_name "$name" || die "invalid snapshot name: $name"
      need_sudo
      sudo -n btrfs subvolume snapshot -r "$WORKSPACE_ROOT" "$SNAPSHOT_DIR/$name" >/dev/null \
        || die "snapshot failed (is $WORKSPACE_ROOT a btrfs subvolume?)"
      ok "Snapshot $SNAPSHOT_DIR/$name"
    }

    cmd_snapshots() { ls -1 "$SNAPSHOT_DIR" 2>/dev/null || true; }

    cmd_rollback() {
      local snap="''${1:-}" ws="''${2:-}"
      { valid_name "$snap" && valid_name "$ws"; } || die "Usage: agentos rollback <snapshot> <workspace>"
      [ -d "$SNAPSHOT_DIR/$snap/$ws" ] || die "No workspace $ws in snapshot $snap"
      warn "This replaces $WORKSPACE_ROOT/$ws with its state in $snap"
      if [ -t 0 ]; then
        local answer
        read -rp "Continue? [y/N] " answer
        [ "$answer" = "y" ] || exit 0
      fi
      need_sudo
      sudo -n rsync -a --delete "$SNAPSHOT_DIR/$snap/$ws/" "$WORKSPACE_ROOT/$ws/"
      ok "Rolled back $ws to $snap"
    }

    # ── main ──────────────────────────────────────────────────────────
    main() {
      local cmd="''${1:-help}"
      shift || true
      case "$cmd" in
        agents)          cmd_agents ;;
        spawn|run)       cmd_spawn "$@" ;;
        list|ls)         cmd_list ;;
        logs)            cmd_logs "$@" ;;
        kill|stop)       cmd_kill "$@" ;;
        shell)           cmd_shell "$@" ;;
        status|st)       cmd_status ;;
        workspace|ws)    cmd_workspace "$@" ;;
        snapshot)        cmd_snapshot "$@" ;;
        snapshots)       cmd_snapshots ;;
        rollback)        cmd_rollback "$@" ;;
        budget)          exec agentos-budget "$@" ;;
        install|i)
          [ -n "''${1:-}" ] || die "Usage: agentos install <package>"
          nix profile install "nixpkgs#$1" ;;
        search)
          [ -n "''${1:-}" ] || die "Usage: agentos search <query>"
          nix search nixpkgs "$1" ;;
        version|--version|-v) cmd_version ;;
        help|--help|-h)  cmd_help ;;
        *)               err "Unknown command: $cmd"; cmd_help; exit 1 ;;
      esac
    }

    main "$@"
  '';

  meta = {
    description = "AgentOS command-line interface";
    mainProgram = "agentos";
    license = lib.licenses.mit;
  };
}
